### ISSUE TITLE
`condition="excludes"` with `groupRelation="or"`

### ISSUE THREAD

**Issue by PiRomant** [ion-storm/sysmon-config#11]
Is `condition="excludes"` correct with `groupRelation="or"`?
https://github.com/ion-storm/sysmon-config/blob/234662c09842988b982c04226f14d6cf3e05123d/sysmonconfig-export.xml#L3767-L3775

**Comment by ion-storm** [comment]
thank you, this was  an error I will correct

**Comment by ion-storm** [comment]
Will be pushed next commit.
