### ISSUE TITLE
Add Antivirus exclusions

### ISSUE THREAD

**Issue by VadimKutia** [ion-storm/sysmon-config#13]
Please add exclusions for ESET and Kaspersky antiviruses in Event ID 3 and Event ID 10 and Event ID 12 & 13 & 14

Example for Kaspersky
ID3
`
			<Image condition="begin with">C:\Program Files (x86)\Kaspersky Lab</Image>
			<Image condition="begin with">C:\Program Files\Kaspersky Lab</Image>`

ID10
`<Rule name="Antivirus" groupRelation="or">
				<SourceImage condition="begin with">C:\Program Files (x86)\Kaspersky Lab</SourceImage>
				<SourceImage condition="begin with">C:\Program Files\Kaspersky Lab</SourceImage>
			</Rule>`

ID14
`<RuleGroup name="RG=RegistryEvent Exclude Group" groupRelation="or">
		<RegistryEvent onmatch="exclude">
			<Image condition="begin with">C:\Program Files (x86)\Kaspersky Lab</Image>
			<Image condition="begin with">C:\Program Files\Kaspersky Lab</Image>
		</RegistryEvent>
	</RuleGroup>`

**Comment by ion-storm** [comment]
will do, thank you!

**Comment by ion-storm** [comment]
@VadimKutia exclusions added, thank you for the contribution!

**Comment by VadimKutia** [comment]
Hello @ion-storm !
Sorry for my English, I'm bad at explaining :)
In ID 10, it is necessary to move this code with exceptions for antiviruses from (RuleGroup name="RG=ProcessAccess Include Group" groupRelation="or")  to the section (RuleGroup name="RG=ProcessAccess Exclude Group" groupRelation="or")

`<Rule name="Antivirus Exclusions" groupRelation="or"> 
				<SourceImage condition="begin with">C:\Program Files (x86)\Kaspersky Lab</SourceImage> 
				<SourceImage condition="begin with">C:\Program Files\Kaspersky Lab</SourceImage>
				<SourceImage condition="begin with">C:\Program Files (x86)\ESET</SourceImage>
				<SourceImage condition="begin with">C:\Program Files\ESET</SourceImage>
</Rule>`

This is necessary so that there are no entries in the logs about the access of antiviruses to processes

In ID 14 you also need to create RuleGroup with onmatch="exclude" for Antivirus Exclusions
This is necessary so as not to log antivirus calls to the registry
Thank you
