### ISSUE TITLE
Create contributing guidelines regarding RuleName field

### ISSUE THREAD

**Issue by cyberkryption** [ion-storm/sysmon-config#17]
There should be a contributing guide for RuleName field so that it remains consistent.

The RuleName field should either reference Mitre Attack details  or be set to None for background or forensic events.

Detection
```<CommandLine name="Attack=T1204,Technique=User Execution,Tactic=Execution,Level=0,Desc=Execution from Archive File,Risk=50" condition="contains">AppData\Local\Temp\7z</CommandLine><!-- exec from 7zip -->```

Background / Forensic
```<CommandLine name="Attack=None,Technique=None,Tactic=None,Level=0,Desc=ScriptFile execution" condition="contains">ScriptFile</CommandLine>```

**Comment by ion-storm** [comment]
I agree, unless of course these can be tagged with MITRE ATT&CK.  Allot that are None, i just havent gotten to yet.  Where do you propose I put this recommendation? Config? @cyberkryption

**Comment by cyberkryption** [comment]
I would put a separate file in repo with contribution guidlines and put a
reference to it in readme.md

Maybe consider a licence as well ?

**Comment by ion-storm** [comment]
I put this in the Readme and the actual config file, license is there.
Thanks!
