### ISSUE TITLE
Current version is blocking October KB's from installing and creates a loop of undoing changes for 24+ hours

### ISSUE THREAD

**Issue by stondino00** [ion-storm/sysmon-config#18]
With Sysmon 14.1 and the current config as of today, it's blocking the installation of any October KB on Windows 11 and 10.  Creates a 24+ hour loop of undoing changes to the update before computer is usable.

**Comment by ion-storm** [comment]
@stondino00 this issue occurred with a previous commit, can you validate that you are on the latest configuration version? 
I am running windows 11 with all updates installed with no issue currently.  If you validate that this is still an issue and provide logs of the file's blocked I will re-open this.

**Comment by stondino00** [comment]
Definitely seems to be your config still.  We tried a different config and did not have the issue with updates.  Thanks

**Comment by ion-storm** [comment]
@stondino00 thanks for the report, I recommend that anyone comment out the FileBlockExe and FileBlockShredding sections in production environments.  Any chance on producing some logs to see what was blocked so we can whitelist?

**Comment by ion-storm** [comment]
@stondino00 I committed an update to remove file shred and executable blocking to the main config, the blocking config can be used at your own risk.  If possible to provide logs of what was blocked so we can whitelist that would be great.  
For now the configuration is safe to use.
