### ISSUE TITLE
Duble configs 

### ISSUE THREAD

**Issue by VadimKutia** [ion-storm/sysmon-config#19]
Hello! I think that the Syssysmonconfig-export_blocking.xml and Syssysmonconfig-export.xml configs are duplicated.

**Comment by NerbalOne** [comment]
@VadimKutia To me they look different. See https://github.com/ion-storm/sysmon-config/commit/a99afce0868b51bd5d06bd69a38eab55456a20f2 to review the differences.

**Comment by VadimKutia** [comment]
![image](https://user-images.githubusercontent.com/113970724/198332349-000eea44-688f-4c4f-8686-11f8461c02f2.png)
The Sysmonconfig-export_blocking.xml and Sysmonconfig-export.xml without ID 27 and ID 28

**Comment by VadimKutia** [comment]
> @VadimKutia To me they look different. See [a99afce](https://github.com/ion-storm/sysmon-config/commit/a99afce0868b51bd5d06bd69a38eab55456a20f2) to review the differences.

In two configs (sysmonconfig-export.xml and sysmonconfig-export_blocking.xml) ID 27 and ID 28 have been removed. Is this correct?

**Comment by NerbalOne** [comment]
@VadimKutia I now see what you are referring to. Yeah I believe sysmonconfig-export_blocking should include ID 27 and 28 while sysmonconfig-export.xml shouldn't.
