### ISSUE TITLE
AV noise

### ISSUE THREAD

**Issue by PiRomant** [ion-storm/sysmon-config#24]
It should most likely be `onmatch="exclude"`

https://github.com/ion-storm/sysmon-config/blame/91c9f540009ca4a94224d38d45d3e4837fc045c0/sysmonconfig-export.xml#L8855-L8860

**Comment by NerbalOne** [comment]
Hey @PiRomant. Are you saying that the rule you linked is noisy and you believe it should be excluded?

**Comment by PiRomant** [comment]
According to  https://github.com/ion-storm/sysmon-config/commit/894a4e4be3ace0600f32639ecca3b128bf4678f2 it was conceived as an exception. It fills 90% of the log.

**Comment by NerbalOne** [comment]
Hey @PiRomant. Thanks for the clarification. I believe this rule should just be deleted.

**Comment by PiRomant** [comment]
Deleting won't help. Need `onmatch="exclude"`

**Comment by NerbalOne** [comment]
Hey @PiRomant. "Rule name="Attack=None,Technique=None,Tactic=None,DS=Windows Registry: Windows Registry Key Modification,Desc=Antivirus Registry Moninitoring" groupRelation="or" is the rule generating all the noise correct? If so, keeping this rule won't be any benefit and it should be deleted. Once deleted, the noise should go away.

**Comment by NerbalOne** [comment]
Hey @PiRomant. I'm going to close this issue. Please delete that rule if its causing a ton of noise. We also might implement this change in the future as I don't see a ton of benefit from this rule.

**Comment by PiRomant** [comment]
Yes, deleting helped
