### ISSUE TITLE
Question on System Performance

### ISSUE THREAD

**Issue by coleJ98** [ion-storm/sysmon-config#7]
Hi, Thanks for putting together this rule set! its brilliant!

I had a question regarding the system performance on standard workstations. A config file with around 3k rules cause any performance issues? How many logs do you receive per 24hr period for a workstation...

I am asking this because I am not sure whether this would be safe for production use or shall I reduce the ruleset? Please let me know your thoughts!

Thanks again!

**Comment by cyberkryption** [comment]
It should be fine, but you will need to tune for ylur own software
environment first

**Comment by b0bbyB** [comment]
Hi - we are having this exact same question. 
Can anyone give any numbers for what kind of performance hit a standard Client PC will take?

We don't want to slow down our PCs (any more than necessary).

@cyberkryption you mention that you need to tune it for own needs? Does that mean it's not a good idea just to take this config file and deploy it blindly?

**Comment by cyberkryption** [comment]
In my view, deloying anything blindly without understanding the detection
it provides and areas it doesnt due to choices made is at best a bzd idea.

At worst, you could miss a detection.

Cheers

Cyberkryption

**Comment by ion-storm** [comment]
A little late to comment but my internal config is now over 7000 lines, no performance issues.
